platform :ios, '9.0'

target 'fastbuy' do

    pod 'GoogleAppMeasurement', '~> 5.2.0'
    pod 'Firebase/Core', '~> 5.9.0'
    pod 'Firebase/Performance', '~> 5.9.0'

    target 'fastbuyTests' do
        inherit! :search_paths
    end

end
